### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by lu1z5ec**
You've been waiting a long time. I'm really, really sorry for being late.
I'm late because of a git pull request issue.

1. Spell Correction
2. Some improvements in Korean translation..

### CODE REVIEW

**Comment by lu1z5ec** [comment]
Ah!! Finally, Goda

**Review by SpriteOvO — APPROVED** [review]
LGTM

**Comment by SpriteOvO** [comment]
@lu1z5ec Thanks! BTW, in the future I'll probably add a text in Settings-About tab for crediting translators, would you like to leave your GitHub name "lu1z5ec" (or your other name?) there?

**Comment by lu1z5ec** [comment]
> Thanks! BTW, in the future I'll probably add a text in Settings-About tab for crediting translators, would you like to leave your GitHub name "lu1z5ec" (or your other name?) there?

No, it's okay.
Not only am I still lacking in skills, but I feel burdened :)

**Pull request merged**
