### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by tGecko**
Added German translation.

I hope this works out well, haven't done this in a long time.

### CODE REVIEW

**Review by SpriteOvO — APPROVED** [review]
LGTM

**Comment by SpriteOvO** [comment]
@tGecko Thanks! BTW, in the future I'll probably add a text in Settings-About tab for crediting translators, would you like to leave your GitHub name "tGecko" (or your other name?) there?

**Comment by tGecko** [comment]
> @tGecko Thanks! BTW, in the future I'll probably add a text in Settings-About tab for crediting translators, would you like to leave your GitHub name "tGecko" (or your other name?) there?

If you decide to add the text, i would prefer if you add my full name, "Thomas Klemenc".
Thank you.

I also tried to build it myself, and maybe dab around in the code a bit, but i wasn't able to completely follow your build instructions.

I always got an error "ObjectNotFound: (RelWithDebInfo>:String)" when executing cmake.

I couldn't manage to solve this issue, as i am not a very experienced developer.

**Comment by SpriteOvO** [comment]
> I always got an error "ObjectNotFound: (RelWithDebInfo>:String)" when executing cmake.

@tGecko `<Debug|RelWithDebInfo>` is all possible values (`Debug` or `RelWithDebInfo`) and you should choose one of them to run.

If you want to compile this project with `Debug` configuration, run:
```
cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=path\to\vcpkg\scripts\buildsystems\vcpkg.cmake ../
cmake --build . --config Debug
```
or with `RelWithDebInfo` configuration, run:
```
cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=path\to\vcpkg\scripts\buildsystems\vcpkg.cmake ../
cmake --build . --config RelWithDebInfo
```

And don't forget to change the path of `vcpkg`.

If you are still encountering problems, let's discuss more in a new issue :)

**Pull request merged**
